### PR TITLE
[WIP] RSS Ticker

### PR DESCRIPTION
**Pull request by jethrogb**
**do not merge**

Yet another Firefox extension bites the dust. I've maintained a Live Bookmarks ticker for many many years but with WebExtensions it's impossible to access Live Bookmarks. I've rebuilt my ticker on top of Brief. I'm combining it with 30(!) extensions that together show the ticker in their browser action icons stacked next to each other. Thanks, Mozilla (again), for making this the only way to get more than 16×16px screen real estate...

You can see what the ticker looks like at `/ui/ticker.html`. If you have any interest in making this or something like this available upstream I'm happy to work with you. Otherwise, I'm happy to keep this patch to myself :smiley:

### CODE REVIEW

**Comment by jethrogb** [comment]
I had an idea to make this more modularized: how about other extensions can subscribe to a `"feedsUpdated"` event from Brief? Brief would listens to subscription requests from other extensions using `runtime.onMessageExternal`. Then, when feeds are updated, it would use `runtime.sendMessage` to send information about the updated feeds/entries. Thoughts?

**Comment by tanriol** [comment]
What API do you want other extensions to have access to? Just "subscribe" and "feedsUpdated", nothing else?

**Comment by jethrogb** [comment]
That would be sufficient for my purposes, yes.

**Comment by tanriol** [comment]
Closing as I don't think this would be of general use with the current implementation. I'd be okay with allowing external extensions to subscribe to Brief's notifications (with user consent and/or using a hidden pref the user needs to set manually) about feed updates, but that should be a separate PR if you're still interested.

**Pull request closed without merging**
